import { SCREENSHOTS_BUCKET, requireSupabase } from './supabase.js'

const EXT_BY_MIME = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/gif': 'gif',
  'image/webp': 'webp',
  'image/svg+xml': 'svg',
  'image/bmp': 'bmp',
}

function extFromMime(mime) {
  return EXT_BY_MIME[mime] ?? 'png'
}

// id is generated by the caller (not here) so it can copy the resulting /s/:id URL to the
// clipboard *before* awaiting this — a clipboard write needs to happen inside the original
// click's user-activation window, which an upload's network round-trip can outlast.
// image: {url, width, height} — annotations: already converted to image-fraction coordinates
// (see rectToFraction/pointToFraction in lib/grid.js) so they're reproducible on any viewport
export async function createShare({ id, image, annotations }) {
  const supabase = requireSupabase()
  const blob = await fetch(image.url).then((r) => r.blob())

  const { error: uploadError } = await supabase.storage
    .from(SCREENSHOTS_BUCKET)
    .upload(`${id}.${extFromMime(blob.type)}`, blob, { contentType: blob.type })
  if (uploadError) throw uploadError

  const {
    data: { publicUrl },
  } = supabase.storage.from(SCREENSHOTS_BUCKET).getPublicUrl(`${id}.${extFromMime(blob.type)}`)

  const { error: insertError } = await supabase.from('shared_tabs').insert({
    id,
    image_url: publicUrl,
    image_width: image.width,
    image_height: image.height,
    annotations,
  })
  if (insertError) throw insertError
}

export async function fetchShare(id) {
  const supabase = requireSupabase()
  const { data, error } = await supabase.from('shared_tabs').select('*').eq('id', id).maybeSingle()
  if (error) throw error
  return data
}
